[package]
name = "eco-sdk"
version = "0.1.0"
edition = "2021"
description = "Rust SDK for embedding E-CO services"
license = "MIT"

[lib]
name = "eco_sdk"
path = "src/lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
eco-core = { path = "../../engines/eco-core" }
