// @generated by tools/generate-ethos-proto.mjs. Do not edit manually.
import { MethodKind, type ServiceType } from "@connectrpc/connect";
import {
  CreateConversationRequest,
  CreateConversationResponse,
  ListConversationsRequest,
  ListConversationsResponse,
  SendMessageRequest,
  SendMessageResponse,
  StreamMessagesRequest,
  StreamMessagesResponse,
  StreamPresenceRequest,
  StreamPresenceResponse,
} from "./ethos_pb";

export const ConversationsService = {
  typeName: "ethos.v1.ConversationsService",
  methods: {
    listConversations: {
      name: "ListConversations",
      I: ListConversationsRequest,
      O: ListConversationsResponse,
      kind: MethodKind.Unary,
    },
    createConversation: {
      name: "CreateConversation",
      I: CreateConversationRequest,
      O: CreateConversationResponse,
      kind: MethodKind.Unary,
    },
    sendMessage: {
      name: "SendMessage",
      I: SendMessageRequest,
      O: SendMessageResponse,
      kind: MethodKind.Unary,
    },
    streamMessages: {
      name: "StreamMessages",
      I: StreamMessagesRequest,
      O: StreamMessagesResponse,
      kind: MethodKind.ServerStreaming,
    },
    streamPresence: {
      name: "StreamPresence",
      I: StreamPresenceRequest,
      O: StreamPresenceResponse,
      kind: MethodKind.ServerStreaming,
    },
  },
} as const satisfies ServiceType;
