name: ether-net

on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev libayatana-appindicator3-dev webkit2gtk-4.1
      - name: Build Ether Net Tauri app
        run: cargo build --manifest-path apps/desktop/ether-net/src-tauri/Cargo.toml
